ParticularPresence.WeatherApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParticularPresence.WeatherApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ParticularPresence.WeatherApplication/Controllers/WeatherController.cs
using Newtonsoft.Json;
using ParticularPresence.WeatherApplication.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ParticularPresence.WeatherApplication.Controllers
{
    public class WeatherController : Controller
    {
        // GET: Weather
        public ActionResult KingstonForcast()
        {
            string url = "http://api.openweathermap.org/data/2.5/forecast?id=3489854&appid=89cf0c0f2efddb2dd16edad131d2f949&units=metric";
            var forcast = MakeRequest(url);
            return View(forcast);          
        }

        public ActionResult MontegoBayForcast()
        {
            string url = "http://api.openweathermap.org/data/2.5/forecast?id=3489460&appid=89cf0c0f2efddb2dd16edad131d2f949&units=metric";
            var forcast = MakeRequest(url);
            return View(forcast);
        }

        public List<WeatherData> MakeRequest(string url)
        {
            string requestUrl = url;
            try
            {
                HttpWebRequest request = WebRequest.Create(requestUrl) as HttpWebRequest;
                HttpWebResponse response = request.GetResponse() as HttpWebResponse;

                string html = string.Empty;
                using (response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream))
                {
                    html = reader.ReadToEnd();
                }
                var info = JsonConvert.DeserializeObject<RootObject>(html);
                var infolist = info.list;

                List<WeatherData> WeatherList = new List<WeatherData>();
                String date = "";

                for (int i = 0; i < infolist.Count; i++)
                {
                    if (date != Convert.ToDateTime(infolist[i].dt_txt).ToShortDateString())
                    {
                        WeatherData weatherdata = new WeatherData();
                        weatherdata.dt_txt = infolist[i].dt_txt;
                        weatherdata.description = infolist[i].weather[0].description;
                        weatherdata.temp = infolist[i].main.temp;
                        weatherdata.humidity = infolist[i].main.humidity;
                        WeatherList.Add(weatherdata);
                        date = Convert.ToDateTime(infolist[i].dt_txt).ToShortDateString();
                    }
                }
                return WeatherList;
            }
            catch (Exception e)
            {
                return null;
            }
        }
    }
}

ParticularPresence.WeatherApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ParticularPresence.WeatherApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ParticularPresence.WeatherApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ParticularPresence.WeatherApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title - Krace Kennedy Weather Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Krace Kennedy Weather Application", "KingstonForcast", "Weather", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kingston Forcast", "KingstonForcast", "Weather")</li>
                    <li>@Html.ActionLink("MontegoBay Forcast", "MontegoBayForcast", "Weather")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="change">
            <footer>
                <p>&copy; @DateTime.Now.Year -Krace Kennedy Weather Application</p>
            </footer>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

ParticularPresence.WeatherApplication/Views/Weather/KingstonForcast.cshtml
@model IEnumerable<ParticularPresence.WeatherApplication.Models.WeatherData>
@{
    ViewBag.Title = "KingstonForcast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="change">
    <h2>Kingston 5 day Forcast</h2>
</div>

@foreach (var item in Model)
{
<div class="col-md-4">
    <div class="change">
        <h3>Date: @Html.DisplayFor(modelItem => item.dt_txt)</h3>
    </div>
    <div class="change">
        <h4>Temperature: @Html.DisplayFor(modelItem => item.temp)°C</h4>
    </div>     
    <div class="change">
        <h4>Description: @Html.DisplayFor(modelItem => item.description)</h4>
    </div>
</div>
}

ParticularPresence.WeatherApplication/Views/Weather/MontegoBayForcast.cshtml
@model IEnumerable<ParticularPresence.WeatherApplication.Models.WeatherData>
@{
    ViewBag.Title = "MontegoBayForcast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="change">
    <h2>Montego Bay 5 day Forcast</h2>
</div>

    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="change">
                <h3>Date: @Html.DisplayFor(modelItem => item.dt_txt)</h3>
            </div>
            <div class="change">
                <h4>Temperature: @Html.DisplayFor(modelItem => item.temp) °C</h4>
            </div>
            <div class="change">
                <h4>Description: @Html.DisplayFor(modelItem => item.description)</h4>
            </div>
        </div>
    }